In [1]:
pip install cvxopt

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
from cvxopt.modeling import variable, op

# ВАРИАНТ 24

Проверим, является ли транспортная задача закрытого типа (объем запасов равен объему потребностей)

In [3]:
290 + 370 + 250 == 140 + 130 + 210 + 270 + 160

True

In [4]:
x = variable(15, 'x')
z=(5*x[0] + 14*x[1] + 8* x[2] + 11*x[3] + 4*x[4] +15* x[5]+ 10*x[6] + 12*x[7] + 13* x[8] + 10* x[9] + 7* x[10] + 9* x[11] + 16* x[12] + 17* x[13] + 23* x[14])  # целевая функция
cond1 = (x[0] + x[1] +x[2] + x[3] + x[4] <= 290)  # условие для первой строки матрицы закупок
cond2 = (x[5] + x[6] +x[7] + x[8] + x[9] <= 370)  #условие для второй строки матрицы закупок
cond3 = (x[10] + x[11] + x[12] + x[13] + x[14] <= 250)  # #условие для третьей строки матрицы закупок
cond4 = (x[0] + x[5] + x[10] == 140)  # условия для 1 столбца
cond5 = (x[1] + x[6] + x[11] == 130)  #условия для 2 столбца
cond6 = (x[2] + x[7] + x[12] == 210)  #условия для 3 столбца
cond7 = (x[3] + x[8] + x[13] == 270)  #условия для 4 столбца
cond8 = (x[4] + x[9] + x[14] == 160)  #условия для 5 столбца

def count(cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8, z):
    trans =op(z,[cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8, (x >= 0)])  #создаём объект модели
    trans.solve(solver='glpk')  #преобразуем задачу оптимизации в линейную программу в матричном виде, а затем решаем ее с помощью solver
    print("Оптимальная стоимость перевозки -",trans.objective.value()[0])
    print("Оптимальный план перевозки груза:")
    for i in [1,6,11]: 
        print(np.array([round(x.value[i-1]), round(x.value[i]),round(x.value[i+1]), round(x.value[i+2]), round(x.value[i+3])]))

count (cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8,z)

Оптимальная стоимость перевозки - 8320.0
Оптимальный план перевозки груза:
[  0   0 130   0 160]
[  0  20  80 270   0]
[140 110   0   0   0]
